services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU20-ubuntu-22.04
    container_name: sqlserver
    environment:
      SA_PASSWORD: "sql2016."
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - sqlserver_net

networks:
  sqlserver_net:
    driver: bridge
