services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU20-ubuntu-22.04
    container_name: sqlserver
    environment:
      SA_PASSWORD: "sql2016."
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - sqlserver_net

  redis:
    image: redis:7-alpine
    container_name: redis
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--requirepass", "${REDIS_PASSWORD}"
    ]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sqlserver_net
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$REDIS_PASSWORD\" ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5
      
networks:
  sqlserver_net:
    driver: bridge

volumes:
  redis_data: